name: Java CI with Maven

on:
  push:
    branches:
      - main  # oder der Branch, den du verwenden möchtest (z. B. master)
  pull_request:
    branches:
      - main  # oder der Branch, den du verwenden möchtest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Stelle sicher, dass dies mit deiner JDK-Version übereinstimmt

      - name: Build and test with Maven
        run: mvn clean install
